import {
  CategoryPage,
  CreateCategoryPage,
  EditCategoryPage,
  DiscountCodePage,
  CreateDiscountCodePage,
  EditDiscountCodePage,
  DonatePromotionPage,
  CreateDonatePromotionPage,
  EditDonatePromotionPage,
  AccountListPage,
  ShowAccountPage,
  ShowDiscountCodePage,
  BannersListPage,
  BannerDetailPage,
  CreateBanners,
  EditBanner,
  TrangDanhSachAccGame,
} from "@pages";

import {
  CreateProducts,
  EditProducts,
  ListOrderPage,
  ProductDetailPage,
  ShowOrderPage,
} from "../pages";
export const adminModules = [
  {
    name: "discountcode",
    list: DiscountCodePage,
    create: CreateDiscountCodePage,
    edit: EditDiscountCodePage,
    show: ShowDiscountCodePage,
    allowedRoles: ["admin"],
  },
  {
    name: "categories",
    list: CategoryPage,
    create: CreateCategoryPage,
    edit: EditCategoryPage,
    allowedRoles: ["admin"],
  },
  {
    name: "categories",
    list: CategoryPage,
    create: CreateCategoryPage,
    edit: EditCategoryPage,
  },
  {
    name: "users",
    list: AccountListPage,
    show: ShowAccountPage,
    allowedRoles: ["admin"],
  },
  {
    name: "products",
    list: TrangDanhSachAccGame,
    show: ProductDetailPage,
    create: CreateProducts,
    edit: EditProducts,
    allowedRoles: ["admin"],
  },
  {
    name: "banners",
    list: BannersListPage,
    show: BannerDetailPage,
    create: CreateBanners,
    edit: EditBanner,
    allowedRoles: ["admin"],
  },
  {
    name: "orders",
    list: ListOrderPage,
    show: ShowOrderPage,
    allowedRoles: ["admin"],
  },
];
